### PR TITLE
Haptics intensity control

### PR DESCRIPTION
**Pull request by zarik5**
#180 #21

As usual, this is not a real fix but a way to manually adjust the controller haptics intensity.

### CODE REVIEW

**Comment by TheWors3** [comment]
Thank you for that, I hope there will be a fix for the sometimes non existant haptics.

**Comment by zarik5** [comment]
@TheWors3 In the next release you will be able to increase haptics intensity on Other tab.

**Comment by heclak** [comment]
Does the server need to be restarted after changing the haptics intensity? I've built this off the latest commit and it doesn't seem to do much. I've tried restarting the server between settings as well. There's probably only a marginal difference if any.

**Comment by zarik5** [comment]
I tried it on the SteamVR home and it seemed to make a difference. Maybe some games require more than a x5?

**Comment by heclak** [comment]
I rebuilt it and tried it again. The difference is very slight for me. Maybe cause I'm too used to the vibration on the WMR controllers which are very much stronger. I tested using Beat Saber on SteamVR (ALVR) and the Quest Beat Saber demo and the vibrations are still weaker after scaling it to x10. I suspect the issue might be with the duration of the haptics or dropped info. The haptics are intermittent when I'm using it. Is that the case for you?

I confirmed that the haptics intensity worked by setting the multiplier to 0. And it does need a server restart for the settings to take. It would be nice if the settings could be updated without a restart. Just like how the pose time offset can be updated without a restart.

**Comment by zarik5** [comment]
If the haptics info are dropped it could be a problem with the sockets implementation. Maybe it will be fixed in the future but not now. In a future version the ability to change certain settings on the fly will be removed but restarting the server will probably be easier.

**Comment by heclak** [comment]
@zarik5 are there plans to re-implement/fix the sockets implementation? I'm still trying to track down the issue for haptics.

**Comment by TheWors3** [comment]
If you use beatsaber steamvr with alvr, put a song and cross the swords so it keeps vibrating you can feel that the vibration starts, kinda slowly decreases, stops and starts again and the behavior repeats. I took a look at the code and while i'm illiterate in regards to that I saw something related to number of haptic samples so I thought maybe the maximum number is reached, it stops and resets until it reaches it again. Probably nothing but something to keep in mind

**Comment by zarik5** [comment]
That is interesting. Probably it isn't a socket problem then. Unfortunately now i'm really busy, it will be a while until I have the time to inspect and fix this bug.

**Comment by TheWors3** [comment]
no problem, I just hope its easy to fix, its the only thing keeping me from using it over virtual desktop which gives me constant controller stuttering

**Pull request merged**
