### PR TITLE
New FFR algorithm (slices)

### PR DESCRIPTION
**Pull request by zarik5**
I propose a new fixed foveated rendering technique. It slices the frames into rectangles, packs them into smaller frames rendering the rectangles in the vision periphery at lower pixel density and the central rectangle at the original pixel density. The cuts are aligned so that the final image is rendered pixel-perfect. This algorithm uses the same variables as the FFR implemented with image distortion.

Other changes in this PR:
* Removed UI bindings for foveation shape ratio. Now fixed to 1.5
* Added combobox for selecting FFR mode; changed text field to slider for foveation strength
* Refactoring FFR variables.

Online demo: https://www.shadertoy.com/view/WddGz8

The following images are obtained with resolution=50%, foveation strength=5.

Input frame no FFR:
frame_normal

Input frame FFR with slices:
frame_slices

Client screenshot no FFR:
client_capture_normal

Client screenshot FFR with slices:
client_capture_slices

### CODE REVIEW

**Comment by JackD83** [comment]
Looks wild, fantastic work! Does it have the same reduction of the video size as the old one? 
Should I merge it right away? I'm currently on a business trip and don't have much time (for vr)

**Comment by zarik5** [comment]
> Does it have the same reduction of the video size as the old one?

In principle this algorithm uses the variables in a completely different way but I added some conversion code so that the compression and the perceived image quality are comparable to the distortion FFR (for equal values of foveation strength)

You can merge it now.

**Comment by JackD83** [comment]
I had some time to test your new algorithm and it looks very good. Is it hard to tweak the parameters a little? In my tests, I noticed that the lower part is much more visible than the other corners. At strength 2 the lower ~20% are very blurred while I can barely see the top or the sides. In Fallout, a lot of menus are shown in that region

**Comment by zarik5** [comment]
In the headset I see that the higher quality region is well centered, but your argument is valid in the sense that in certain scenes (e.g. natural landscapes) there is more useful details in the lower half of the screen. I can add an offset parameter to adjust the vertical position of the region.

**Comment by JackD83** [comment]
An offset would be great. You are right that it is perfectly centered. I just played a few games and most of them have their main interaction area more at the bottom where your hands are.

**Comment by zarik5** [comment]
Implemented vertical offset
https://github.com/JackD83/ALVR/pull/48
https://github.com/JackD83/ALVRClient/pull/4

**Pull request merged**
