### PR TITLE
Added color correction (brightness, contrast, saturation, gamma)

### PR DESCRIPTION
**Pull request by zarik5**

### CODE REVIEW

**Comment by zarik5** [comment]
Before resolving the merge conflicts I would like to point that on commit e419848 the buffer offset label is not working right for negative values. Besides, @JackD83 I suggest you to not reuse the old buffer settings entry because the first time I ran your latest server version there was already a non zero value and that can create problems for those who don't notice this.

**Comment by JackD83** [comment]
@zarik5 thx! I noticed it myself. I started to redo the whole video tab to make it responsive anyway. The whole ui is a mess

**Comment by JackD83** [comment]
I manually merged the UI. Please test the result. Are you sure about the values? If I enter gamma 2.2 the image is very bright

**Comment by zarik5** [comment]
Thanks. The color correction controls work fine, the gamma value 2.2 is the constant used to convert sRGB to RGB color space, it is meant to be used if some games use the wrong color space for some reason. Or for example, if there is a dark scene and you want to see more clearly you can use a value of 1.5.
Now the buffer offset slider work fine. Before I thought the label was referred to the buffer *offset*, and so I was expecting a value of 0 when I moved the slider cursor in the middle. Can you also add a label for the buffer offset? It would be useful to know where the zero is, if you moved the slider by mistake. Sorry if I'm nitpicking.

**Comment by JackD83** [comment]
No nitpicking at all. You do all the heavy lifting anyways :) (still waiting for the sliced encoding :P )

I know how the color correction works, I was just wondering why steam home and most games look correct, and others seem to require gamma 2.2?! Is it possible to detect the color space from the texture that comes from steamvr? The thing is that I can now enter gamma 2.2 to correct a game but then steam home will look horrible in the same session.

**Comment by zarik5** [comment]
ALVR is itself creating the textures, which are then sent to SteamVR to be rendered on. The requested format is stored in SwapTextureSetDesc_t. When it's time to render the texture layers, ALVR creates the ShaderResourceViews using the same formats as the corresponding textures, so I don't see any problem here.
I tried VRChat but I didn't see any problem with gamma. I verified that the format was always SRGB. Do you have any examples of games that have the wrong gamma?

**Pull request merged**
