### PR TITLE
Add Presets tab + Boneworks controllers fix

### PR DESCRIPTION
**Pull request by zarik5**
* Add "Presets" tab with "Revert settings to default", "Boneworks controllers fix" and "Set default controller offsets;
* Add configurable controller position and rotation offset + "Other" tab UI refactoring.

I lost at least 1h and an half trying to understand why on the numericUpDowns that I added, when positioned in certain places and when I set a negative value, close and reopen ALVR, the value was clamped to zero. Then I restarted Visual Studio and the sucessive builds didn't had this bug anymore. Also sometimes the tabs get shuffled and the merge diff becomes unreadable. TBH we should scrap WinForms and use WPF or UWP but I have no time for this.

@JackD83 For fixes for other games, please tell me what to add, or else merge this and add them yourself.

### CODE REVIEW

**Comment by JackD83** [comment]
I'm still working on the warped image in some games, but has noting to do with controllers. 
Spend countless hours without any results so far

WinForms is really horrible, but it would be a lot of work to replace it

**Comment by zarik5** [comment]
Are there any free games that have the warping problem? So I can take a look at it.

**Comment by JackD83** [comment]
https://www.digitalcombatsimulator.com/ should have the problem

its issue #88

**Comment by zarik5** [comment]
Thanks!

**Pull request merged**
