### PR TITLE
Made some reverts for improved stability.

### PR DESCRIPTION
**Pull request by FingrMastr**
Restored the LOWDELAY nvenc profile as it seems to not cause decoder freeze.

Restored to a count of 16 the max buffer for ref frames, and restored Intrarefresh to maximize recovery from errors in streaming.

### CODE REVIEW

**Comment by FingrMastr** [comment]
Intra refresh is a feature used in streaming scenarios prone to errors and low bandwidth. This feature can be used to generate waves of rows of Intra macro blocks. This is useful to gradually recover from errors that may have happened on client side. So for example in case of errors, recovery from these situations is much faster.

Usually, it is used to avoid artifacts in critical situations. Maybe it could be better to have a UI switch to enable it.

**Comment by FingrMastr** [comment]
A little note. For some reason, someone enabled the “extra latency mode” in the VRapi code. In a comment is stated that disabling it causes frame drop and stuttering, but I’m not experiencing that behavior. Also in VRapi the “perfThread” is set on main and not renderer. I’ll test some more on these, but maybe we can think of some “performance flags” in the ALVR ui Window, with these settings and also with intra refresh for particular situations...

**Comment by JackD83** [comment]
With intra refresh I had constant macro blocks and playing like that was no fun at all. I have to test the intra refresh together with the higher ref frames, maybe the combination fixes that. 
Extra latency mode is enabled to get some extra time for the decoder to decode the image and let the async timewarp handle the movement. I think the stuttering kicks in when the decoder takes too long. I will also check the thread settings

**Comment by FingrMastr** [comment]
Raising cpu and gpu levels to 4 and disabling extra latency mode in my case helped a lot with overall smoothness, with no visible quality diminution.

I’m trying to include some code to periodically flush the mediaCodec, but it is very tied with worker threads and input/output queues, so obviously without stopping decoder completely, I’m getting some exceptions... Not sure if a complete stop/start would cause acceptable momentary lag...

**Comment by JackD83** [comment]
I just tried the changes in this PR and have to say that I still have this bad image quality. I tried to make a screenshot, but I'm unable to do so. This could be something the decoder on the quest is producing. The encoded video looked fine.

Changing the encoder profile is OK

**Comment by FingrMastr** [comment]
Today I tried to play with H264 and the perf degradation is WAAAAY weaker and longer. I definitely think that it’s something about decoding app-side that’s causing the mess.

Regarding the intra refresh, I have only slight blockyness every 10 seconds, barely perceptible. I think that the different behavior on different systems could be for slightly different hw revisions of Quest. What do you think?

**Comment by JackD83** [comment]
It looks like the decoder is a little fragile. Would be nice to see what other apps use for the decoding. From oculus is known that they use h264 and bypass java and use the decoder directly. Something we cant do. 
Is it OK if i decline this PR and add the change of the encoding profile manually?

I will try and mess a little with the queues tomorrow

**Comment by FingrMastr** [comment]
Of course!! After all, intra refresh is only an error resilience feature. It’s not solving smithing in my case.

I already tried to flush queues (frame and NAL) at regular intervals. Nothing. Maybe we could try a complete reset of decoder. I’m trying to figure out what are the steps sequence to do a complete stop of decoder and a restart. I think we have to stop the DecoderThread loop, then clear input and output queues, then flush codec, then restart the codec/loop...

**Comment by MPfaffe** [comment]
Hi guys, 

I also noticed performance drops after about 15 minutes (until then it is absolutely enjoyable: 72 fps Client and server fps, 0 paket loss) in every VR session with ALVR.
I want to submit my observations to the topic, maybe it helps to solve the problem :-):

1. without sound streaming over ALVR it seems to take longer until the performance drops happen
2. it seems that first the "client fps" drop (down to 40 fps and alternates up to the 72 fps; decoding performance decreases?) and later (5seconds) biginns the network paket loss, the "server fps" were rock solid 72 fps (seen in the "server"-diagnostics area in ALVR during auto-gameplay in Assetto Corsa).

Maybe the snapdragon chipset throttles after a time (due to e.g. overheating)? Or it goes into an energy suspension mode?

system:
R5 2600
16  gb Ram
RTX 2080 ti
Oculus Quest
ASUS RT AC2900 (5 GHz)

**Comment by JackD83** [comment]
@FingrMastr could you please try :cpu and gpu level 0 and disabling extra latency mode
Played a long period without any issues. I was connected to the PC and profiling.

@MPfaffe chipset throttles could really be the problem

**Comment by MPfaffe** [comment]
Is it possible to control the internal fan of the oculus quest?

if it is a temperature issue, the fan seems not to speed up... 
maybe the overheating is not recognized by the chipset due to temperature sensor placing. The throttling of chipset (e.g. to prevent the device from damage) could be performed because of detected failures in decoding.

**Comment by FingrMastr** [comment]
This throttling problem could explain the prolonged stable period with our last “stability reverts”...

**Comment by MPfaffe** [comment]
If it is the problem, the question is why?

maybe the longterm workload is too high and deviates from the specification?
Some websites speak of "3840*2160p/60 fps @ 10 bit color information @ common bitrate"-decoding by the snapdragon 835...
What Information has the output stream of alvr server? (I assume @alvr server:"100%" 2880*1600/72 fps @ XYZ bit color information @ bitrate according to "alvrserver setting")

1. Resolution shall be no problem (3840*2160 vs. 2880*1600)
2. Framerate deviation will increase the workload of the Quest-decoder but it is necessary (60fps vs. 72fps)
3. The converting of colourinformation will increase the workload (10 bit vs. XYZ bit) --> what colour information has the encoded and streamed (ALVR Server) video? Nvidia HEVC encodes in 8, 10 or 12 bit!
4. Too high incoming bitrate will also increase the workload (common bitrates vs. bitrate according "alvrserver setting")--> setting for good quality @ common bitrate is necessary...
5. Does the whole bitstream arrive at the Quest-decoder?
6. How works the decoding on the quest? Is it a per-eye parallel decoding (two tasks for the decoder) or one 2880*1600 video decoding? The way the quest is decoding could also have an impact on the workload...

Just some thoughtful transitions, i'm not an expert :-D

**Comment by FingrMastr** [comment]
@JackD83 sorry to say perf degradation still there, even with cpu and gpu
at zero level... Also, did not know cpu&gpu levels settings are from 0 to
3. There is no 4 (LOL).

A little more: on the last three tests, I restarted the app and played for
around the same time until the FUBAR occurs... It's not the throttling. Or
at least, not ONLY.

Il giorno sab 26 ott 2019 alle ore 17:49 JackD83 <notifications@github.com>
ha scritto:

**Comment by JackD83** [comment]
For the Quest, there is a 4 :P

Please continue the discussion in #70

**Pull request merged**
