### PR TITLE
fix format specification syntax of wchar.

### LINKED ISSUE #171: Get sound device failed
### Bug reports:
On startup immediately showing:
`Get sound device failed: System.Runtime.InteropServices.SEHException (-2147467259/0x80004005)`

#### Environement
CPU: AMD Ryzen 3900X
GPU: Nvidia GTX 970
Windows 10 18363.778
ALVR Experimental v10
Audio: mother board, Aorus elite X570 wifi
Sound device list:
圖片
Sound input device list:
圖片

- [v ] I ran "add_firewall_rules.bat" as adimistrator and checked that the ports are open in the firewall
- [v ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

### PR DESCRIPTION
**Pull request by ohtaketakeshi**
resolve #171 
When ALVR.exe call driver_alvr_server.dll's GetSoundDevices function, internal LogDriver function failed to execute because format specification syntax of wchar was incorrect.
I fixed format specification of wchar in alvr_server project.

### CODE REVIEW

**Comment by JackD83** [comment]
I merged this without checking and it was a bad idea :( 
Now getSoundDevices fails if the string is not a wchar with a std:range_error. Reverting from %ls to %s fixes it

**Comment by ohtaketakeshi** [comment]
In my environment, changing wchar syntax to %ls works fine.
Could you please tell me where the std :: range_error is occurring?

2020年5月2日(土) 17:29 JackD83 <notifications@github.com>:

**Comment by JackD83** [comment]
The error occurs with german umlaute: 

LogDriver("umlaut test: %ls", L"ÖÜÄöüä");

I have an audio device called "Kopfhörer (Oculus Virtual Audio Device)" -> The Oculus link headphones

**Comment by ohtaketakeshi** [comment]
The error occurs in the ToWstring function. The function is trying to convert a string to a wstring by treating the string as UTF-8, but it's not UTF-8, so an error occurs in wstring_convert.
The wchar format seems to be correct with %ls. If %s is given, the stored string is incorrect.

**Pull request merged**
